name: IGEVStereo
max_disp: 192
train_iters: 22
valid_iters: 32
instance:
  _target_: model.igev_stereo.IGEVStereo
  args:
    hidden_dims: [128, 128, 128]
    corr_levels: 2
    corr_radius: 4
    n_downsample: 2
    n_gru_layers: 3
    max_disp: 192