defaults:
  - model: stable_diffusion.yaml
  - _self_

seed: 666
gpus: ${oc.env:CUDA_VISIBLE_DEVICES, '0,1,2,3'}

accelerator:
  _target_: accelerate.Accelerator
  mixed_precision: fp16
  gradient_accumulation_steps: 4
  dataloader_config:
    _target_: accelerate.DataLoaderConfiguration
    split_batches: True
    use_seedable_sampler: True 
  log_with: wandb

tracker:
  project_name: ZeroStereo-StereoGen
  init_kwargs:
    wandb:
      entity: windsrain
      name: StereoGen

train_set:
  TartanAir:
    instance:
      _target_: dataset.inpaint_dataset.TartanAir
      aug_params:
        crop_size: [512, 512]
        random_gaussian: null
        color_jitter:
          brightness: [0.6, 1.4]
          contrast: [0.6, 1.4]
          saturation: [0, 1.4]
          hue: 0.5
          asymmetric_prob: 0
        random_erase: null
        random_scale: null
        y_jitter: False
  CREStereoDataset:
    instance:
      _target_: dataset.inpaint_dataset.CREStereoDataset
      aug_params:
        crop_size: [512, 512]
        random_gaussian: null
        color_jitter:
          brightness: [0.6, 1.4]
          contrast: [0.6, 1.4]
          saturation: [0, 1.4]
          hue: 0.5
          asymmetric_prob: 0
        random_erase: null
        random_scale: null
        y_jitter: False
  FallingThings:
    instance:
      _target_: dataset.inpaint_dataset.FallingThings
      aug_params:
        crop_size: [512, 512]
        random_gaussian: null
        color_jitter:
          brightness: [0.6, 1.4]
          contrast: [0.6, 1.4]
          saturation: [0, 1.4]
          hue: 0.5
          asymmetric_prob: 0
        random_erase: null
        random_scale: null
        y_jitter: False
  SceneFlow:
    instance:
      _target_: dataset.inpaint_dataset.SceneFlow
      aug_params:
        crop_size: [512, 512]
        random_gaussian: null
        color_jitter:
          brightness: [0.6, 1.4]
          contrast: [0.6, 1.4]
          saturation: [0, 1.4]
          hue: 0.5
          asymmetric_prob: 0
        random_erase: null
        random_scale: null
        y_jitter: False
  VKITTI2:
    instance:
      _target_: dataset.inpaint_dataset.VKITTI2
      aug_params:
        crop_size: [512, 512]
        random_gaussian: null
        color_jitter:
          brightness: [0.6, 1.4]
          contrast: [0.6, 1.4]
          saturation: [0, 1.4]
          hue: 0.5
          asymmetric_prob: 0
        random_erase: null
        random_scale: null
        y_jitter: False

train_loader:
  split: False
  batch_size_per_gpu: null
  total_batch_size: 8
  param:
    batch_size: null
    num_workers: null
    pin_memory: True
    shuffle: True
    drop_last: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-5

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 2e-5
  total_steps: 50000
  pct_start: 0.01
  cycle_momentum: False
  anneal_strategy: linear

save_freq: 5000
save_path: checkpoint/stereogen
